import { Link } from "react-router-dom";
import { Stethoscope } from "lucide-react";

export const Impressum = () => (
  <main className="min-h-screen bg-background px-5 py-16 text-foreground"><section className="mx-auto max-w-3xl"><Link className="text-primary" to="/">← Zurück</Link><Stethoscope className="mt-8 size-8 text-primary" /><h1 className="mt-4 font-display text-5xl font-bold">Impressum</h1><div className="mt-8 space-y-5 text-muted-foreground"><p><strong className="text-foreground">Dr. Alina Thordarson</strong><br />Ärztin für Allgemeinmedizin<br />Quellenstraße 18–20, 2763 Neusiedl</p><p>Telefon: 02632/73177</p><p>Berufsbezeichnung: Ärztin für Allgemeinmedizin, verliehen in Österreich. Zuständige Kammer: Österreichische Ärztekammer / Ärztekammer Niederösterreich.</p><p>Informationen gemäß §5 ECG, §14 UGB, §63 GewO und §25 MedienG. Inhaltliche Verantwortung: Dr. Alina Thordarson.</p><p>Diese Website dient der allgemeinen Information und ersetzt keine persönliche ärztliche Beratung, Diagnose oder Behandlung.</p></div></section></main>
);

export const Datenschutz = () => (
  <main className="min-h-screen bg-background px-5 py-16 text-foreground"><section className="mx-auto max-w-3xl"><Link className="text-primary" to="/">← Zurück</Link><h1 className="mt-8 font-display text-5xl font-bold">Datenschutzerklärung</h1><div className="mt-8 space-y-5 text-muted-foreground"><p>Wir verarbeiten personenbezogene Daten ausschließlich zur Bearbeitung von Terminanfragen, Medikamentenanfragen, Kontaktanfragen und zur sicheren Nutzung des Patientenportals.</p><p>Verarbeitete Daten können Name, Geburtsdatum, Kontaktdaten, Versicherungsart, medizinisches Anliegen und Anfrage-Status umfassen. Die Verarbeitung erfolgt auf Grundlage Ihrer Anfrage, gesetzlicher Dokumentationspflichten und berechtigter organisatorischer Interessen der Ordination.</p><p>Ihre Daten werden nicht für Werbung verkauft oder an unbefugte Dritte weitergegeben. Technisch notwendige Cookies dienen Sicherheit, Formularfunktion und Einwilligungsverwaltung.</p><p>Sie haben nach DSGVO Rechte auf Auskunft, Berichtigung, Löschung, Einschränkung, Datenübertragbarkeit und Beschwerde bei der Datenschutzbehörde, soweit keine gesetzlichen Aufbewahrungspflichten entgegenstehen.</p><p>Medizinische Notfälle dürfen nicht über Webformulare übermittelt werden. Rufen Sie in Notfällen 112.</p></div></section></main>
);
